services:
  db-service:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

  ia-service:
    build:
      context: ./backend/ia-service
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    depends_on:
      - db-service


volumes:
  postgres_data:


